// Mocks generated by Mockito 5.4.2 from annotations
// in portfolio_flutter/test/modules/uisplash/bloc/uisplash_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'uisplash_bloc_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RouteRepositoryMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteRepositoryMock extends _i1.Mock
    implements _i2.RouteRepositoryMock {
  MockRouteRepositoryMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> save(String? typeScreen) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [typeScreen],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<String> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
  @override
  _i3.Future<void> clean() => (super.noSuchMethod(
        Invocation.method(
          #clean,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
