name: portfolio_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter_svg: ^1.1.6
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.3
  loading_animation_widget: ^1.2.0+4
  equatable: ^2.0.5
  retrofit: ^4.0.1
  logger: any
  json_serializable: ^6.7.1
  dio: ^5.2.1+1
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.0
  uuid: ^3.0.7

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1
  mockito: ^5.4.2
  build_runner: ^2.4.6
  modular_test: ^2.0.0
  bloc_test: ^9.1.3
  retrofit_generator: ^7.0.8
  http_mock_adapter: ^0.4.4

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/json/