// Mocks generated by Mockito 5.4.2 from annotations
// in portfolio_flutter/test/modules/uisplash/uisplash_pages_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i15;

import 'package:auto_route/auto_route.dart' as _i7;
import 'package:auto_route/src/matcher/route_matcher.dart' as _i9;
import 'package:auto_route/src/router/controller/navigation_history/navigation_history_base.dart'
    as _i10;
import 'package:auto_route/src/router/controller/pageless_routes_observer.dart'
    as _i8;
import 'package:flutter/material.dart' as _i6;
import 'package:flutter_bloc/flutter_bloc.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:portfolio_flutter/modules/core/data/hand_shake_repository.dart'
    as _i3;
import 'package:portfolio_flutter/modules/core/data/route_repository.dart'
    as _i2;
import 'package:portfolio_flutter/modules/core/security/keys.dart' as _i4;
import 'package:portfolio_flutter/modules/uisplash/bloc/uisplash_bloc_event.dart'
    as _i13;
import 'package:portfolio_flutter/modules/uisplash/bloc/uisplash_bloc_state.dart'
    as _i5;

import 'uisplash_pages_test.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRouteRepository_0 extends _i1.SmartFake
    implements _i2.RouteRepository {
  _FakeRouteRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHandShakeRepository_1 extends _i1.SmartFake
    implements _i3.HandShakeRepository {
  _FakeHandShakeRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeys_2 extends _i1.SmartFake implements _i4.Keys {
  _FakeKeys_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUiSplashBlocState_3 extends _i1.SmartFake
    implements _i5.UiSplashBlocState {
  _FakeUiSplashBlocState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalKey_4 extends _i1.SmartFake implements _i6.LocalKey {
  _FakeLocalKey_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePendingRoutesHandler_5 extends _i1.SmartFake
    implements _i7.PendingRoutesHandler {
  _FakePendingRoutesHandler_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePagelessRoutesObserver_6 extends _i1.SmartFake
    implements _i8.PagelessRoutesObserver {
  _FakePagelessRoutesObserver_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActiveGuardObserver_7 extends _i1.SmartFake
    implements _i7.ActiveGuardObserver {
  _FakeActiveGuardObserver_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_8<T extends _i6.State<_i6.StatefulWidget>>
    extends _i1.SmartFake implements _i6.GlobalKey<T> {
  _FakeGlobalKey_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteCollection_9 extends _i1.SmartFake
    implements _i7.RouteCollection {
  _FakeRouteCollection_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoRoutePage_10<T> extends _i1.SmartFake
    implements _i7.AutoRoutePage<T> {
  _FakeAutoRoutePage_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteMatcher_11 extends _i1.SmartFake implements _i9.RouteMatcher {
  _FakeRouteMatcher_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteData_12 extends _i1.SmartFake implements _i7.RouteData {
  _FakeRouteData_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNavigationHistory_13 extends _i1.SmartFake
    implements _i10.NavigationHistory {
  _FakeNavigationHistory_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUrlState_14 extends _i1.SmartFake implements _i7.UrlState {
  _FakeUrlState_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRootStackRouter_15 extends _i1.SmartFake
    implements _i7.RootStackRouter {
  _FakeRootStackRouter_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteMatch_16<T> extends _i1.SmartFake implements _i7.RouteMatch<T> {
  _FakeRouteMatch_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoutingController_17 extends _i1.SmartFake
    implements _i7.RoutingController {
  _FakeRoutingController_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UiSplashBlocMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockUiSplashBlocMock extends _i1.Mock implements _i11.UiSplashBlocMock {
  MockUiSplashBlocMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RouteRepository get routeRepository => (super.noSuchMethod(
        Invocation.getter(#routeRepository),
        returnValue: _FakeRouteRepository_0(
          this,
          Invocation.getter(#routeRepository),
        ),
      ) as _i2.RouteRepository);
  @override
  _i3.HandShakeRepository get handShakeRepository => (super.noSuchMethod(
        Invocation.getter(#handShakeRepository),
        returnValue: _FakeHandShakeRepository_1(
          this,
          Invocation.getter(#handShakeRepository),
        ),
      ) as _i3.HandShakeRepository);
  @override
  _i4.Keys get key => (super.noSuchMethod(
        Invocation.getter(#key),
        returnValue: _FakeKeys_2(
          this,
          Invocation.getter(#key),
        ),
      ) as _i4.Keys);
  @override
  _i5.UiSplashBlocState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUiSplashBlocState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.UiSplashBlocState);
  @override
  _i12.Stream<_i5.UiSplashBlocState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<_i5.UiSplashBlocState>.empty(),
      ) as _i12.Stream<_i5.UiSplashBlocState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  void add(_i13.UiSplashBlocEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i13.UiSplashBlocEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i5.UiSplashBlocState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i13.UiSplashBlocEvent>(
    _i14.EventHandler<E, _i5.UiSplashBlocState>? handler, {
    _i14.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i14.Transition<_i13.UiSplashBlocEvent, _i5.UiSplashBlocState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  void onChange(_i14.Change<_i5.UiSplashBlocState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UiBottomSheetMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockUiBottomSheetMock extends _i1.Mock implements _i11.UiBottomSheetMock {
  MockUiBottomSheetMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void show({
    required _i6.BuildContext? context,
    required String? title,
    required String? text,
    required String? btnText,
    required Function? onBtnClick,
    dynamic enableDrag = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #show,
          [],
          {
            #context: context,
            #title: title,
            #text: text,
            #btnText: btnText,
            #onBtnClick: onBtnClick,
            #enableDrag: enableDrag,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppLocalizationMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizationMock extends _i1.Mock
    implements _i11.AppLocalizationMock {
  MockAppLocalizationMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set context(_i6.BuildContext? context) => super.noSuchMethod(
        Invocation.setter(
          #context,
          context,
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StackRouterMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockStackRouterMock extends _i1.Mock implements _i11.StackRouterMock {
  MockStackRouterMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.LocalKey get key => (super.noSuchMethod(
        Invocation.getter(#key),
        returnValue: _FakeLocalKey_4(
          this,
          Invocation.getter(#key),
        ),
      ) as _i6.LocalKey);
  @override
  _i7.PendingRoutesHandler get pendingRoutesHandler => (super.noSuchMethod(
        Invocation.getter(#pendingRoutesHandler),
        returnValue: _FakePendingRoutesHandler_5(
          this,
          Invocation.getter(#pendingRoutesHandler),
        ),
      ) as _i7.PendingRoutesHandler);
  @override
  _i8.PagelessRoutesObserver get pagelessRoutesObserver => (super.noSuchMethod(
        Invocation.getter(#pagelessRoutesObserver),
        returnValue: _FakePagelessRoutesObserver_6(
          this,
          Invocation.getter(#pagelessRoutesObserver),
        ),
      ) as _i8.PagelessRoutesObserver);
  @override
  _i7.ActiveGuardObserver get activeGuardObserver => (super.noSuchMethod(
        Invocation.getter(#activeGuardObserver),
        returnValue: _FakeActiveGuardObserver_7(
          this,
          Invocation.getter(#activeGuardObserver),
        ),
      ) as _i7.ActiveGuardObserver);
  @override
  int get stateHash => (super.noSuchMethod(
        Invocation.getter(#stateHash),
        returnValue: 0,
      ) as int);
  @override
  _i6.GlobalKey<_i6.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_8<_i6.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i6.GlobalKey<_i6.NavigatorState>);
  @override
  _i7.RouteCollection get routeCollection => (super.noSuchMethod(
        Invocation.getter(#routeCollection),
        returnValue: _FakeRouteCollection_9(
          this,
          Invocation.getter(#routeCollection),
        ),
      ) as _i7.RouteCollection);
  @override
  _i7.PageBuilder get pageBuilder => (super.noSuchMethod(
        Invocation.getter(#pageBuilder),
        returnValue: (_i7.RouteData data) => _FakeAutoRoutePage_10<dynamic>(
          this,
          Invocation.getter(#pageBuilder),
        ),
      ) as _i7.PageBuilder);
  @override
  _i9.RouteMatcher get matcher => (super.noSuchMethod(
        Invocation.getter(#matcher),
        returnValue: _FakeRouteMatcher_11(
          this,
          Invocation.getter(#matcher),
        ),
      ) as _i9.RouteMatcher);
  @override
  _i7.RouteData get current => (super.noSuchMethod(
        Invocation.getter(#current),
        returnValue: _FakeRouteData_12(
          this,
          Invocation.getter(#current),
        ),
      ) as _i7.RouteData);
  @override
  _i7.RouteData get topRoute => (super.noSuchMethod(
        Invocation.getter(#topRoute),
        returnValue: _FakeRouteData_12(
          this,
          Invocation.getter(#topRoute),
        ),
      ) as _i7.RouteData);
  @override
  bool get hasPagelessTopRoute => (super.noSuchMethod(
        Invocation.getter(#hasPagelessTopRoute),
        returnValue: false,
      ) as bool);
  @override
  List<_i7.AutoRoutePage<dynamic>> get stack => (super.noSuchMethod(
        Invocation.getter(#stack),
        returnValue: <_i7.AutoRoutePage<dynamic>>[],
      ) as List<_i7.AutoRoutePage<dynamic>>);
  @override
  bool get ignorePopCompleters => (super.noSuchMethod(
        Invocation.getter(#ignorePopCompleters),
        returnValue: false,
      ) as bool);
  @override
  set ignorePopCompleters(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #ignorePopCompleters,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i7.RoutingController> get childControllers => (super.noSuchMethod(
        Invocation.getter(#childControllers),
        returnValue: <_i7.RoutingController>[],
      ) as List<_i7.RoutingController>);
  @override
  _i10.NavigationHistory get navigationHistory => (super.noSuchMethod(
        Invocation.getter(#navigationHistory),
        returnValue: _FakeNavigationHistory_13(
          this,
          Invocation.getter(#navigationHistory),
        ),
      ) as _i10.NavigationHistory);
  @override
  _i7.UrlState get urlState => (super.noSuchMethod(
        Invocation.getter(#urlState),
        returnValue: _FakeUrlState_14(
          this,
          Invocation.getter(#urlState),
        ),
      ) as _i7.UrlState);
  @override
  String get currentPath => (super.noSuchMethod(
        Invocation.getter(#currentPath),
        returnValue: '',
      ) as String);
  @override
  String get currentUrl => (super.noSuchMethod(
        Invocation.getter(#currentUrl),
        returnValue: '',
      ) as String);
  @override
  List<_i7.RouteData> get stackData => (super.noSuchMethod(
        Invocation.getter(#stackData),
        returnValue: <_i7.RouteData>[],
      ) as List<_i7.RouteData>);
  @override
  bool get managedByWidget => (super.noSuchMethod(
        Invocation.getter(#managedByWidget),
        returnValue: false,
      ) as bool);
  @override
  bool get isTopMost => (super.noSuchMethod(
        Invocation.getter(#isTopMost),
        returnValue: false,
      ) as bool);
  @override
  bool get canNavigateBack => (super.noSuchMethod(
        Invocation.getter(#canNavigateBack),
        returnValue: false,
      ) as bool);
  @override
  _i7.RootStackRouter get root => (super.noSuchMethod(
        Invocation.getter(#root),
        returnValue: _FakeRootStackRouter_15(
          this,
          Invocation.getter(#root),
        ),
      ) as _i7.RootStackRouter);
  @override
  bool get isRoot => (super.noSuchMethod(
        Invocation.getter(#isRoot),
        returnValue: false,
      ) as bool);
  @override
  _i7.RouteMatch<dynamic> get topMatch => (super.noSuchMethod(
        Invocation.getter(#topMatch),
        returnValue: _FakeRouteMatch_16<dynamic>(
          this,
          Invocation.getter(#topMatch),
        ),
      ) as _i7.RouteMatch<dynamic>);
  @override
  _i7.RouteData get routeData => (super.noSuchMethod(
        Invocation.getter(#routeData),
        returnValue: _FakeRouteData_12(
          this,
          Invocation.getter(#routeData),
        ),
      ) as _i7.RouteData);
  @override
  bool get hasEntries => (super.noSuchMethod(
        Invocation.getter(#hasEntries),
        returnValue: false,
      ) as bool);
  @override
  int get pageCount => (super.noSuchMethod(
        Invocation.getter(#pageCount),
        returnValue: 0,
      ) as int);
  @override
  List<_i7.RouteMatch<dynamic>> get currentSegments => (super.noSuchMethod(
        Invocation.getter(#currentSegments),
        returnValue: <_i7.RouteMatch<dynamic>>[],
      ) as List<_i7.RouteMatch<dynamic>>);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i12.Future<void> reevaluateGuards() => (super.noSuchMethod(
        Invocation.method(
          #reevaluateGuards,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  bool canPop({
    bool? ignoreChildRoutes = false,
    bool? ignoreParentRoutes = false,
    bool? ignorePagelessRoutes = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #canPop,
          [],
          {
            #ignoreChildRoutes: ignoreChildRoutes,
            #ignoreParentRoutes: ignoreParentRoutes,
            #ignorePagelessRoutes: ignorePagelessRoutes,
          },
        ),
        returnValue: false,
      ) as bool);
  @override
  _i12.Future<T?> pushWidget<T extends Object?>(
    _i6.Widget? widget, {
    _i6.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
    bool? opaque = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushWidget,
          [widget],
          {
            #transitionBuilder: transitionBuilder,
            #fullscreenDialog: fullscreenDialog,
            #transitionDuration: transitionDuration,
            #opaque: opaque,
          },
        ),
        returnValue: _i12.Future<T?>.value(),
      ) as _i12.Future<T?>);
  @override
  _i12.Future<T?> pushNativeRoute<T extends Object?>(_i6.Route<T>? route) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNativeRoute,
          [route],
        ),
        returnValue: _i12.Future<T?>.value(),
      ) as _i12.Future<T?>);
  @override
  _i12.Future<bool> pop<T extends Object?>([T? result]) => (super.noSuchMethod(
        Invocation.method(
          #pop,
          [result],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #popForced,
          [result],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool removeLast() => (super.noSuchMethod(
        Invocation.method(
          #removeLast,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  void removeRoute(
    _i7.RouteData? route, {
    bool? notify = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeRoute,
          [route],
          {#notify: notify},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i12.Future<T?> push<T extends Object?>(
    _i7.PageRouteInfo<dynamic>? route, {
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i12.Future<T?>.value(),
      ) as _i12.Future<T?>);
  @override
  _i12.Future<T?> replace<T extends Object?>(
    _i7.PageRouteInfo<dynamic>? route, {
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replace,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i12.Future<T?>.value(),
      ) as _i12.Future<T?>);
  @override
  _i12.Future<void> pushAll(
    List<_i7.PageRouteInfo<dynamic>>? routes, {
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushAll,
          [routes],
          {#onFailure: onFailure},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  _i12.Future<void> popAndPushAll(
    List<_i7.PageRouteInfo<dynamic>>? routes, {
    dynamic onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #popAndPushAll,
          [routes],
          {#onFailure: onFailure},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  _i12.Future<void> replaceAll(
    List<_i7.PageRouteInfo<dynamic>>? routes, {
    _i7.OnNavigationFailure? onFailure,
    bool? updateExistingRoutes = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAll,
          [routes],
          {
            #onFailure: onFailure,
            #updateExistingRoutes: updateExistingRoutes,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  void popUntilRoot() => super.noSuchMethod(
        Invocation.method(
          #popUntilRoot,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i12.Future<T?> popAndPush<T extends Object?, TO extends Object?>(
    _i7.PageRouteInfo<dynamic>? route, {
    TO? result,
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #popAndPush,
          [route],
          {
            #result: result,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i12.Future<T?>.value(),
      ) as _i12.Future<T?>);
  @override
  bool removeUntil(
    _i7.RouteDataPredicate? predicate, {
    bool? scoped = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeUntil,
          [predicate],
          {#scoped: scoped},
        ),
        returnValue: false,
      ) as bool);
  @override
  void popUntil(
    _i6.RoutePredicate? predicate, {
    bool? scoped = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#scoped: scoped},
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool removeWhere(
    _i7.RouteDataPredicate? predicate, {
    bool? notify = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWhere,
          [predicate],
          {#notify: notify},
        ),
        returnValue: false,
      ) as bool);
  @override
  void updateDeclarativeRoutes(List<_i7.PageRouteInfo<dynamic>>? routes) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDeclarativeRoutes,
          [routes],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i12.Future<void> navigateAll(
    List<_i7.RouteMatch<dynamic>>? routes, {
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateAll,
          [routes],
          {#onFailure: onFailure},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  _i12.Future<T?> pushAndPopUntil<T extends Object?>(
    _i7.PageRouteInfo<dynamic>? route, {
    required _i6.RoutePredicate? predicate,
    bool? scopedPopUntil = true,
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushAndPopUntil,
          [route],
          {
            #predicate: predicate,
            #scopedPopUntil: scopedPopUntil,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i12.Future<T?>.value(),
      ) as _i12.Future<T?>);
  @override
  _i12.Future<T?> replaceNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceNamed,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i12.Future<T?>.value(),
      ) as _i12.Future<T?>);
  @override
  _i12.Future<T?> pushNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamed,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i12.Future<T?>.value(),
      ) as _i12.Future<T?>);
  @override
  void popUntilRouteWithName(
    String? name, {
    bool? scoped = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntilRouteWithName,
          [name],
          {#scoped: scoped},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void popUntilRouteWithPath(
    String? path, {
    bool? scoped = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntilRouteWithPath,
          [path],
          {#scoped: scoped},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void markUrlStateForReplace() => super.noSuchMethod(
        Invocation.method(
          #markUrlStateForReplace,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void attachChildController(_i7.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(
          #attachChildController,
          [childController],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeChildController(_i7.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(
          #removeChildController,
          [childController],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyAll({bool? forceUrlRebuild = false}) => super.noSuchMethod(
        Invocation.method(
          #notifyAll,
          [],
          {#forceUrlRebuild: forceUrlRebuild},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i12.Future<void> navigateNamed(
    String? path, {
    bool? includePrefixMatches = false,
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateNamed,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
  @override
  List<_i7.HierarchySegment> currentHierarchy({
    bool? asPath = false,
    bool? ignorePending = false,
    bool? ignoreParams = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #currentHierarchy,
          [],
          {
            #asPath: asPath,
            #ignorePending: ignorePending,
            #ignoreParams: ignoreParams,
          },
        ),
        returnValue: <_i7.HierarchySegment>[],
      ) as List<_i7.HierarchySegment>);
  @override
  bool isRouteActive(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #isRouteActive,
          [routeName],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool isRouteDataActive(_i7.RouteData? data) => (super.noSuchMethod(
        Invocation.method(
          #isRouteDataActive,
          [data],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool isPathActive(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isPathActive,
          [path],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i7.RouteMatch<dynamic>? match(_i7.PageRouteInfo<dynamic>? route) =>
      (super.noSuchMethod(Invocation.method(
        #match,
        [route],
      )) as _i7.RouteMatch<dynamic>?);
  @override
  _i12.Future<dynamic> navigate(
    _i7.PageRouteInfo<dynamic>? route, {
    _i7.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigate,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i12.Future<dynamic>.value(),
      ) as _i12.Future<dynamic>);
  @override
  void navigateBack() => super.noSuchMethod(
        Invocation.method(
          #navigateBack,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void back() => super.noSuchMethod(
        Invocation.method(
          #back,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void pushPathState(Object? state) => super.noSuchMethod(
        Invocation.method(
          #pushPathState,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #topMostRouter,
          [],
          {#ignorePagelessRoutes: ignorePagelessRoutes},
        ),
        returnValue: _FakeRoutingController_17(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
      ) as _i7.RoutingController);
  @override
  void updateRouteData(_i7.RouteData? data) => super.noSuchMethod(
        Invocation.method(
          #updateRouteData,
          [data],
        ),
        returnValueForMissingStub: null,
      );
  @override
  T? innerRouterOf<T extends _i7.RoutingController>(String? routeName) =>
      (super.noSuchMethod(Invocation.method(
        #innerRouterOf,
        [routeName],
      )) as T?);
  @override
  _i12.Future<bool> popTop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
        Invocation.method(
          #popTop,
          [result],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
  @override
  _i7.PageRouteInfo<dynamic>? buildPageRoute(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #buildPageRoute,
        [path],
        {#includePrefixMatches: includePrefixMatches},
      )) as _i7.PageRouteInfo<dynamic>?);
  @override
  List<_i7.PageRouteInfo<dynamic>>? buildPageRoutesStack(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #buildPageRoutesStack,
        [path],
        {#includePrefixMatches: includePrefixMatches},
      )) as List<_i7.PageRouteInfo<dynamic>>?);
  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [KeyRepositoryMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyRepositoryMock extends _i1.Mock implements _i11.KeyRepositoryMock {
  MockKeyRepositoryMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<void> cleanSeedSaved() => (super.noSuchMethod(
        Invocation.method(
          #cleanSeedSaved,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}
