// Mocks generated by Mockito 5.4.2 from annotations
// in portfolio_flutter/test/modules/uiauth/uiauth_pages_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i13;

import 'package:auto_route/auto_route.dart' as _i4;
import 'package:auto_route/src/matcher/route_matcher.dart' as _i6;
import 'package:auto_route/src/router/controller/navigation_history/navigation_history_base.dart'
    as _i7;
import 'package:auto_route/src/router/controller/pageless_routes_observer.dart'
    as _i5;
import 'package:flutter/material.dart' as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:portfolio_flutter/modules/core/localizations/app_localization.dart'
    as _i12;
import 'package:portfolio_flutter/modules/uiauth/bloc/uiauth_bloc_event.dart'
    as _i10;
import 'package:portfolio_flutter/modules/uiauth/bloc/uiauth_bloc_state.dart'
    as _i2;

import 'uiauth_pages_test.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUiAuthBlocState_0 extends _i1.SmartFake
    implements _i2.UiAuthBlocState {
  _FakeUiAuthBlocState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_1 extends _i1.SmartFake implements _i3.Widget {
  _FakeWidget_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeLocalKey_2 extends _i1.SmartFake implements _i3.LocalKey {
  _FakeLocalKey_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePendingRoutesHandler_3 extends _i1.SmartFake
    implements _i4.PendingRoutesHandler {
  _FakePendingRoutesHandler_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePagelessRoutesObserver_4 extends _i1.SmartFake
    implements _i5.PagelessRoutesObserver {
  _FakePagelessRoutesObserver_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActiveGuardObserver_5 extends _i1.SmartFake
    implements _i4.ActiveGuardObserver {
  _FakeActiveGuardObserver_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_6<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake implements _i3.GlobalKey<T> {
  _FakeGlobalKey_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteCollection_7 extends _i1.SmartFake
    implements _i4.RouteCollection {
  _FakeRouteCollection_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoRoutePage_8<T> extends _i1.SmartFake
    implements _i4.AutoRoutePage<T> {
  _FakeAutoRoutePage_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteMatcher_9 extends _i1.SmartFake implements _i6.RouteMatcher {
  _FakeRouteMatcher_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteData_10 extends _i1.SmartFake implements _i4.RouteData {
  _FakeRouteData_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNavigationHistory_11 extends _i1.SmartFake
    implements _i7.NavigationHistory {
  _FakeNavigationHistory_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUrlState_12 extends _i1.SmartFake implements _i4.UrlState {
  _FakeUrlState_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRootStackRouter_13 extends _i1.SmartFake
    implements _i4.RootStackRouter {
  _FakeRootStackRouter_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteMatch_14<T> extends _i1.SmartFake implements _i4.RouteMatch<T> {
  _FakeRouteMatch_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoutingController_15 extends _i1.SmartFake
    implements _i4.RoutingController {
  _FakeRoutingController_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UiAuthBlocMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockUiAuthBlocMock extends _i1.Mock implements _i8.UiAuthBlocMock {
  MockUiAuthBlocMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UiAuthBlocState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUiAuthBlocState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.UiAuthBlocState);
  @override
  _i9.Stream<_i2.UiAuthBlocState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i2.UiAuthBlocState>.empty(),
      ) as _i9.Stream<_i2.UiAuthBlocState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  void add(_i10.UiAuthBlocEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onEvent(_i10.UiAuthBlocEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i2.UiAuthBlocState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void on<E extends _i10.UiAuthBlocEvent>(
    _i11.EventHandler<E, _i2.UiAuthBlocState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onTransition(
          _i11.Transition<_i10.UiAuthBlocEvent, _i2.UiAuthBlocState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  void onChange(_i11.Change<_i2.UiAuthBlocState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StringsMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockStringsMock extends _i1.Mock implements _i8.StringsMock {
  MockStringsMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String onlyNumber(String? text) => (super.noSuchMethod(
        Invocation.method(
          #onlyNumber,
          [text],
        ),
        returnValue: '',
      ) as String);
}

/// A class which mocks [AppLocalizationMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizationMock extends _i1.Mock
    implements _i8.AppLocalizationMock {
  MockAppLocalizationMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set context(_i3.BuildContext? context) => super.noSuchMethod(
        Invocation.setter(
          #context,
          context,
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoadingMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadingMock extends _i1.Mock implements _i8.LoadingMock {
  MockLoadingMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Widget showLoading(_i12.AppLocalization? localization) =>
      (super.noSuchMethod(
        Invocation.method(
          #showLoading,
          [localization],
        ),
        returnValue: _FakeWidget_1(
          this,
          Invocation.method(
            #showLoading,
            [localization],
          ),
        ),
      ) as _i3.Widget);
}

/// A class which mocks [StackRouterMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockStackRouterMock extends _i1.Mock implements _i8.StackRouterMock {
  MockStackRouterMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.LocalKey get key => (super.noSuchMethod(
        Invocation.getter(#key),
        returnValue: _FakeLocalKey_2(
          this,
          Invocation.getter(#key),
        ),
      ) as _i3.LocalKey);
  @override
  _i4.PendingRoutesHandler get pendingRoutesHandler => (super.noSuchMethod(
        Invocation.getter(#pendingRoutesHandler),
        returnValue: _FakePendingRoutesHandler_3(
          this,
          Invocation.getter(#pendingRoutesHandler),
        ),
      ) as _i4.PendingRoutesHandler);
  @override
  _i5.PagelessRoutesObserver get pagelessRoutesObserver => (super.noSuchMethod(
        Invocation.getter(#pagelessRoutesObserver),
        returnValue: _FakePagelessRoutesObserver_4(
          this,
          Invocation.getter(#pagelessRoutesObserver),
        ),
      ) as _i5.PagelessRoutesObserver);
  @override
  _i4.ActiveGuardObserver get activeGuardObserver => (super.noSuchMethod(
        Invocation.getter(#activeGuardObserver),
        returnValue: _FakeActiveGuardObserver_5(
          this,
          Invocation.getter(#activeGuardObserver),
        ),
      ) as _i4.ActiveGuardObserver);
  @override
  int get stateHash => (super.noSuchMethod(
        Invocation.getter(#stateHash),
        returnValue: 0,
      ) as int);
  @override
  _i3.GlobalKey<_i3.NavigatorState> get navigatorKey => (super.noSuchMethod(
        Invocation.getter(#navigatorKey),
        returnValue: _FakeGlobalKey_6<_i3.NavigatorState>(
          this,
          Invocation.getter(#navigatorKey),
        ),
      ) as _i3.GlobalKey<_i3.NavigatorState>);
  @override
  _i4.RouteCollection get routeCollection => (super.noSuchMethod(
        Invocation.getter(#routeCollection),
        returnValue: _FakeRouteCollection_7(
          this,
          Invocation.getter(#routeCollection),
        ),
      ) as _i4.RouteCollection);
  @override
  _i4.PageBuilder get pageBuilder => (super.noSuchMethod(
        Invocation.getter(#pageBuilder),
        returnValue: (_i4.RouteData data) => _FakeAutoRoutePage_8<dynamic>(
          this,
          Invocation.getter(#pageBuilder),
        ),
      ) as _i4.PageBuilder);
  @override
  _i6.RouteMatcher get matcher => (super.noSuchMethod(
        Invocation.getter(#matcher),
        returnValue: _FakeRouteMatcher_9(
          this,
          Invocation.getter(#matcher),
        ),
      ) as _i6.RouteMatcher);
  @override
  _i4.RouteData get current => (super.noSuchMethod(
        Invocation.getter(#current),
        returnValue: _FakeRouteData_10(
          this,
          Invocation.getter(#current),
        ),
      ) as _i4.RouteData);
  @override
  _i4.RouteData get topRoute => (super.noSuchMethod(
        Invocation.getter(#topRoute),
        returnValue: _FakeRouteData_10(
          this,
          Invocation.getter(#topRoute),
        ),
      ) as _i4.RouteData);
  @override
  bool get hasPagelessTopRoute => (super.noSuchMethod(
        Invocation.getter(#hasPagelessTopRoute),
        returnValue: false,
      ) as bool);
  @override
  List<_i4.AutoRoutePage<dynamic>> get stack => (super.noSuchMethod(
        Invocation.getter(#stack),
        returnValue: <_i4.AutoRoutePage<dynamic>>[],
      ) as List<_i4.AutoRoutePage<dynamic>>);
  @override
  bool get ignorePopCompleters => (super.noSuchMethod(
        Invocation.getter(#ignorePopCompleters),
        returnValue: false,
      ) as bool);
  @override
  set ignorePopCompleters(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #ignorePopCompleters,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i4.RoutingController> get childControllers => (super.noSuchMethod(
        Invocation.getter(#childControllers),
        returnValue: <_i4.RoutingController>[],
      ) as List<_i4.RoutingController>);
  @override
  _i7.NavigationHistory get navigationHistory => (super.noSuchMethod(
        Invocation.getter(#navigationHistory),
        returnValue: _FakeNavigationHistory_11(
          this,
          Invocation.getter(#navigationHistory),
        ),
      ) as _i7.NavigationHistory);
  @override
  _i4.UrlState get urlState => (super.noSuchMethod(
        Invocation.getter(#urlState),
        returnValue: _FakeUrlState_12(
          this,
          Invocation.getter(#urlState),
        ),
      ) as _i4.UrlState);
  @override
  String get currentPath => (super.noSuchMethod(
        Invocation.getter(#currentPath),
        returnValue: '',
      ) as String);
  @override
  String get currentUrl => (super.noSuchMethod(
        Invocation.getter(#currentUrl),
        returnValue: '',
      ) as String);
  @override
  List<_i4.RouteData> get stackData => (super.noSuchMethod(
        Invocation.getter(#stackData),
        returnValue: <_i4.RouteData>[],
      ) as List<_i4.RouteData>);
  @override
  bool get managedByWidget => (super.noSuchMethod(
        Invocation.getter(#managedByWidget),
        returnValue: false,
      ) as bool);
  @override
  bool get isTopMost => (super.noSuchMethod(
        Invocation.getter(#isTopMost),
        returnValue: false,
      ) as bool);
  @override
  bool get canNavigateBack => (super.noSuchMethod(
        Invocation.getter(#canNavigateBack),
        returnValue: false,
      ) as bool);
  @override
  _i4.RootStackRouter get root => (super.noSuchMethod(
        Invocation.getter(#root),
        returnValue: _FakeRootStackRouter_13(
          this,
          Invocation.getter(#root),
        ),
      ) as _i4.RootStackRouter);
  @override
  bool get isRoot => (super.noSuchMethod(
        Invocation.getter(#isRoot),
        returnValue: false,
      ) as bool);
  @override
  _i4.RouteMatch<dynamic> get topMatch => (super.noSuchMethod(
        Invocation.getter(#topMatch),
        returnValue: _FakeRouteMatch_14<dynamic>(
          this,
          Invocation.getter(#topMatch),
        ),
      ) as _i4.RouteMatch<dynamic>);
  @override
  _i4.RouteData get routeData => (super.noSuchMethod(
        Invocation.getter(#routeData),
        returnValue: _FakeRouteData_10(
          this,
          Invocation.getter(#routeData),
        ),
      ) as _i4.RouteData);
  @override
  bool get hasEntries => (super.noSuchMethod(
        Invocation.getter(#hasEntries),
        returnValue: false,
      ) as bool);
  @override
  int get pageCount => (super.noSuchMethod(
        Invocation.getter(#pageCount),
        returnValue: 0,
      ) as int);
  @override
  List<_i4.RouteMatch<dynamic>> get currentSegments => (super.noSuchMethod(
        Invocation.getter(#currentSegments),
        returnValue: <_i4.RouteMatch<dynamic>>[],
      ) as List<_i4.RouteMatch<dynamic>>);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<void> reevaluateGuards() => (super.noSuchMethod(
        Invocation.method(
          #reevaluateGuards,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  bool canPop({
    bool? ignoreChildRoutes = false,
    bool? ignoreParentRoutes = false,
    bool? ignorePagelessRoutes = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #canPop,
          [],
          {
            #ignoreChildRoutes: ignoreChildRoutes,
            #ignoreParentRoutes: ignoreParentRoutes,
            #ignorePagelessRoutes: ignorePagelessRoutes,
          },
        ),
        returnValue: false,
      ) as bool);
  @override
  _i9.Future<T?> pushWidget<T extends Object?>(
    _i3.Widget? widget, {
    _i3.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
    bool? opaque = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushWidget,
          [widget],
          {
            #transitionBuilder: transitionBuilder,
            #fullscreenDialog: fullscreenDialog,
            #transitionDuration: transitionDuration,
            #opaque: opaque,
          },
        ),
        returnValue: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);
  @override
  _i9.Future<T?> pushNativeRoute<T extends Object?>(_i3.Route<T>? route) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNativeRoute,
          [route],
        ),
        returnValue: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);
  @override
  _i9.Future<bool> pop<T extends Object?>([T? result]) => (super.noSuchMethod(
        Invocation.method(
          #pop,
          [result],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #popForced,
          [result],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool removeLast() => (super.noSuchMethod(
        Invocation.method(
          #removeLast,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  void removeRoute(
    _i4.RouteData? route, {
    bool? notify = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #removeRoute,
          [route],
          {#notify: notify},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<T?> push<T extends Object?>(
    _i4.PageRouteInfo<dynamic>? route, {
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #push,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);
  @override
  _i9.Future<T?> replace<T extends Object?>(
    _i4.PageRouteInfo<dynamic>? route, {
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replace,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);
  @override
  _i9.Future<void> pushAll(
    List<_i4.PageRouteInfo<dynamic>>? routes, {
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushAll,
          [routes],
          {#onFailure: onFailure},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> popAndPushAll(
    List<_i4.PageRouteInfo<dynamic>>? routes, {
    dynamic onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #popAndPushAll,
          [routes],
          {#onFailure: onFailure},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> replaceAll(
    List<_i4.PageRouteInfo<dynamic>>? routes, {
    _i4.OnNavigationFailure? onFailure,
    bool? updateExistingRoutes = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAll,
          [routes],
          {
            #onFailure: onFailure,
            #updateExistingRoutes: updateExistingRoutes,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  void popUntilRoot() => super.noSuchMethod(
        Invocation.method(
          #popUntilRoot,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<T?> popAndPush<T extends Object?, TO extends Object?>(
    _i4.PageRouteInfo<dynamic>? route, {
    TO? result,
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #popAndPush,
          [route],
          {
            #result: result,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);
  @override
  bool removeUntil(
    _i4.RouteDataPredicate? predicate, {
    bool? scoped = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeUntil,
          [predicate],
          {#scoped: scoped},
        ),
        returnValue: false,
      ) as bool);
  @override
  void popUntil(
    _i3.RoutePredicate? predicate, {
    bool? scoped = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#scoped: scoped},
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool removeWhere(
    _i4.RouteDataPredicate? predicate, {
    bool? notify = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWhere,
          [predicate],
          {#notify: notify},
        ),
        returnValue: false,
      ) as bool);
  @override
  void updateDeclarativeRoutes(List<_i4.PageRouteInfo<dynamic>>? routes) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDeclarativeRoutes,
          [routes],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<void> navigateAll(
    List<_i4.RouteMatch<dynamic>>? routes, {
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateAll,
          [routes],
          {#onFailure: onFailure},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<T?> pushAndPopUntil<T extends Object?>(
    _i4.PageRouteInfo<dynamic>? route, {
    required _i3.RoutePredicate? predicate,
    bool? scopedPopUntil = true,
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushAndPopUntil,
          [route],
          {
            #predicate: predicate,
            #scopedPopUntil: scopedPopUntil,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);
  @override
  _i9.Future<T?> replaceNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceNamed,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);
  @override
  _i9.Future<T?> pushNamed<T extends Object?>(
    String? path, {
    bool? includePrefixMatches = false,
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamed,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);
  @override
  void popUntilRouteWithName(
    String? name, {
    bool? scoped = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntilRouteWithName,
          [name],
          {#scoped: scoped},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void popUntilRouteWithPath(
    String? path, {
    bool? scoped = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntilRouteWithPath,
          [path],
          {#scoped: scoped},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void markUrlStateForReplace() => super.noSuchMethod(
        Invocation.method(
          #markUrlStateForReplace,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void attachChildController(_i4.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(
          #attachChildController,
          [childController],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeChildController(_i4.RoutingController? childController) =>
      super.noSuchMethod(
        Invocation.method(
          #removeChildController,
          [childController],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyAll({bool? forceUrlRebuild = false}) => super.noSuchMethod(
        Invocation.method(
          #notifyAll,
          [],
          {#forceUrlRebuild: forceUrlRebuild},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i9.Future<void> navigateNamed(
    String? path, {
    bool? includePrefixMatches = false,
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateNamed,
          [path],
          {
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  List<_i4.HierarchySegment> currentHierarchy({
    bool? asPath = false,
    bool? ignorePending = false,
    bool? ignoreParams = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #currentHierarchy,
          [],
          {
            #asPath: asPath,
            #ignorePending: ignorePending,
            #ignoreParams: ignoreParams,
          },
        ),
        returnValue: <_i4.HierarchySegment>[],
      ) as List<_i4.HierarchySegment>);
  @override
  bool isRouteActive(String? routeName) => (super.noSuchMethod(
        Invocation.method(
          #isRouteActive,
          [routeName],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool isRouteDataActive(_i4.RouteData? data) => (super.noSuchMethod(
        Invocation.method(
          #isRouteDataActive,
          [data],
        ),
        returnValue: false,
      ) as bool);
  @override
  bool isPathActive(String? path) => (super.noSuchMethod(
        Invocation.method(
          #isPathActive,
          [path],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i4.RouteMatch<dynamic>? match(_i4.PageRouteInfo<dynamic>? route) =>
      (super.noSuchMethod(Invocation.method(
        #match,
        [route],
      )) as _i4.RouteMatch<dynamic>?);
  @override
  _i9.Future<dynamic> navigate(
    _i4.PageRouteInfo<dynamic>? route, {
    _i4.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigate,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);
  @override
  void navigateBack() => super.noSuchMethod(
        Invocation.method(
          #navigateBack,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void back() => super.noSuchMethod(
        Invocation.method(
          #back,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void pushPathState(Object? state) => super.noSuchMethod(
        Invocation.method(
          #pushPathState,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #topMostRouter,
          [],
          {#ignorePagelessRoutes: ignorePagelessRoutes},
        ),
        returnValue: _FakeRoutingController_15(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
      ) as _i4.RoutingController);
  @override
  void updateRouteData(_i4.RouteData? data) => super.noSuchMethod(
        Invocation.method(
          #updateRouteData,
          [data],
        ),
        returnValueForMissingStub: null,
      );
  @override
  T? innerRouterOf<T extends _i4.RoutingController>(String? routeName) =>
      (super.noSuchMethod(Invocation.method(
        #innerRouterOf,
        [routeName],
      )) as T?);
  @override
  _i9.Future<bool> popTop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
        Invocation.method(
          #popTop,
          [result],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
  @override
  _i4.PageRouteInfo<dynamic>? buildPageRoute(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #buildPageRoute,
        [path],
        {#includePrefixMatches: includePrefixMatches},
      )) as _i4.PageRouteInfo<dynamic>?);
  @override
  List<_i4.PageRouteInfo<dynamic>>? buildPageRoutesStack(
    String? path, {
    bool? includePrefixMatches = true,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #buildPageRoutesStack,
        [path],
        {#includePrefixMatches: includePrefixMatches},
      )) as List<_i4.PageRouteInfo<dynamic>>?);
  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
