name: Verificando teste unitário.

on:
  pull_request:
    branches:
      - develop
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Faz o checkout do repositório
        uses: actions/checkout@v2

      - name: Configurando node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalação do firebase tools
        run: npm install -g firebase-tools

      - name: Obtem arquivo em base64 para arquivo de certificado
        run: |
          cd android
          mkdir key
          cd key
          echo "${{ secrets.KEY_BASE64 }}" | base64 -d > raphaeldesenvolvimento.jks

      - name: Configura flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Gerando arquivos auto gerados do flutter
        run: flutter pub run build_runner build -d

      - name: Instala dependências
        run: flutter pub get

      - name: Roda teste de cobertura
        run: flutter test --coverage
        if: success()
